#!/bin/bash

git clone https://github.com/bucharest-gold/s2i-nodejs.git
cd s2i-nodejs

echo "---> onbuild using centos7"
docker build -t tests2inodejscentos7 .

echo "---> onbuild using fedora"
docker build --file Dockerfile.fedora -t tests2inodejsfedora .

echo "---> onbuild using rhel7-atomic"
docker build --file Dockerfile.atomic -t tests2inodejsfedora .

echo "---> onbuild using rhel7"
docker build --file Dockerfile.rhel7 -t tests2inodejsfedora .
