#!/bin/bash

oc cluster up
oc login -u system:admin

echo "---> Creating s2i-nodejs build with centos7 Dockerfile"
oc new-build --binary --name=s2inodejs -l app=s2inodejs --dockerfile Dockerfile.centos7

echo "---> Building s2i-nodejs app"
npm install
oc start-build s2inodejs --from-dir=. --follow

echo "---> Starting s2i-nodejs"
oc new-app s2inodejs -l app=s2inodejs
sleep 60
oc expose svc/s2inodejs
sleep 60

curl $(oc get routes | awk '{print $2}' | grep xip.io)
printf "\n"
echo "---> App running"

###
oc new-project fedora

echo "---> Creating s2i-nodejs build with fedora Dockerfile"
oc new-build --binary --name=s2inodejs -l app=s2inodejs --dockerfile Dockerfile.fedora

echo "---> Building s2i-nodejs app"
npm install
oc start-build s2inodejs --from-dir=. --follow

echo "---> Starting s2i-nodejs"
oc new-app s2inodejs -l app=s2inodejs
sleep 60
oc expose svc/s2inodejs
sleep 60

curl $(oc get routes | awk '{print $2}' | grep xip.io)
printf "\n"
echo "---> App running"
