#!/bin/bash

echo "FROM bucharestgold/centos7-nodejs:7.8.0" > Dockerfile

oc cluster up
echo "---> New build with centos7"
oc new-build --binary --name=s2inodejs -l app=s2inodejs
npm install
oc start-build s2inodejs --from-dir=. --follow
echo "---> Starting app"
oc new-app s2inodejs -l app=s2inodejs
sleep 120
oc expose svc/s2inodejs
sleep 120
curl $(oc get routes | awk '{print $2}' | grep xip.io)
printf "\n"
echo "---> App running"

#oc new-project fedora
#echo "FROM bucharestgold/fedora-nodejs:7.8.0" > Dockerfile
#echo "---> New build with fedora"
#oc new-build --binary --name=s2inodejs -l app=s2inodejs
#npm install
#oc start-build s2inodejs --from-dir=. --follow
#echo "---> Starting app"
#oc new-app s2inodejs -l app=s2inodejs
#sleep 120
#oc expose svc/s2inodejs
#sleep 120
#curl $(oc get routes | awk '{print $2}' | grep xip.io)
#printf "\n"
#echo "---> App running"

oc cluster down