dist: trusty
before_script:
  - sudo apt install python-pip
  - pip install docker-squash
  - wget https://github.com/openshift/source-to-image/releases/download/v1.1.4/source-to-image-1.1.4-870b273-linux-amd64.tar.gz
  - tar xvzf source-to-image-1.1.4-870b273-linux-amd64.tar.gz
  - sudo mv s2i /usr/bin
script:
  - make test
