dist: trusty
before_script:
  - sudo apt install python-pip
  - pip install docker-squash
  - wget https://github.com/openshift/source-to-image/releases/download/v1.1.4/source-to-image-1.1.4-870b273-linux-amd64.tar.gz
  - sudo tar xvzOf source-to-image-1.1.4-870b273-linux-amd64.tar.gz s2i > /usr/bin/s2i
  - sudo chmod 755 /usr/bin/s2i
script:
  - make test
notifications:
  irc: "chat.freenode.net#brass-monkey"