dist: trusty
before_script:
  - sudo apt-get purge docker-engine
  - sudo apt-get autoremove --purge docker-engine
  - sudo apt-get -y install apt-transport-https ca-certificates
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo mount --make-shared /
  - sudo service docker stop
  - sudo sed -i 's/DOCKER_OPTS=\"/DOCKER_OPTS=\"--insecure-registry 172.30.0.0\/16 /' /etc/default/docker
  - sudo service docker start
  - pip install docker-squash
  - wget https://github.com/openshift/source-to-image/releases/download/v1.1.5/source-to-image-v1.1.5-4dd7721-linux-amd64.tar.gz
  - tar xvzOf source-to-image-v1.1.5-4dd7721-linux-amd64.tar.gz > s2i.bin
  - sudo mv s2i.bin /usr/bin/s2i
  - sudo chmod 755 /usr/bin/s2i
  - wget https://github.com/openshift/origin/releases/download/v1.4.1/openshift-origin-client-tools-v1.4.1-3f9807a-linux-64bit.tar.gz
  - tar xvzOf openshift-origin-client-tools-v1.4.1-3f9807a-linux-64bit.tar.gz > oc.bin
  - sudo mv oc.bin /usr/bin/oc
  - sudo chmod 755 /usr/bin/oc
script:
  - make test TARGET=centos7
  - make test TARGET=atomic
  - make test TARGET=fedora
  - make test TARGET=rhel7
  - make onbuild TARGET=centos7 VERSIONS=7.8.0
  - make onbuild TARGET=atomic VERSIONS=7.8.0
  - make onbuild TARGET=fedora VERSIONS=7.8.0
  - make onbuild TARGET=rhel7 VERSIONS=7.8.0
  - test/onbuild-test
#  - test/onbuild-openshift
notifications:
  irc: "chat.freenode.net#brass-monkey"